import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Product from './models/Product.js';

dotenv.config();
await mongoose.connect(process.env.MONGO_URI);
await Product.deleteMany();

await Product.insertMany([
  {
    name: 'Classic White Tee',
    description: 'Essential everyday cotton t-shirt with a relaxed fit.',
    price: 29.99,
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500'],
    category: 'Men',
    brand: 'DRIP Basics',
    sizes: ['XS','S','M','L','XL','XXL'],
    colors: ['White','Black','Gray'],
    stock: 50,
    isFeatured: true,
    isNew: false,
  },
  {
    name: 'Slim Fit Chinos',
    description: 'Smart casual chinos perfect for work or weekend.',
    price: 59.99,
    images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=500'],
    category: 'Men',
    brand: 'DRIP Studio',
    sizes: ['28','30','32','34','36'],
    colors: ['Beige','Navy','Olive'],
    stock: 30,
    isFeatured: true,
    isNew: true,
  },
  {
    name: 'Floral Wrap Dress',
    description: 'Elegant wrap dress with a vibrant floral print.',
    price: 79.99,
    images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500'],
    category: 'Women',
    brand: 'DRIP Studio',
    sizes: ['XS','S','M','L','XL'],
    colors: ['Floral Blue','Floral Pink'],
    stock: 25,
    isFeatured: true,
    isNew: true,
  },
  {
    name: 'High Waist Jeans',
    description: 'Classic high waist skinny jeans with stretch denim.',
    price: 89.99,
    images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500'],
    category: 'Women',
    brand: 'DRIP Denim',
    sizes: ['24','26','28','30','32'],
    colors: ['Light Blue','Dark Blue','Black'],
    stock: 40,
    isFeatured: false,
    isNew: true,
  },
  {
    name: 'Air Runner Pro',
    description: 'Lightweight running shoes with cushioned sole.',
    price: 119.99,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500'],
    category: 'Shoes',
    brand: 'DRIP Sport',
    sizes: ['6','7','8','9','10','11','12'],
    colors: ['White/Red','Black/White','Gray/Blue'],
    stock: 35,
    isFeatured: true,
    isNew: true,
  },
  {
    name: 'Street Leather Sneakers',
    description: 'Premium leather sneakers for everyday street style.',
    price: 149.99,
    images: ['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500'],
    category: 'Shoes',
    brand: 'DRIP Street',
    sizes: ['6','7','8','9','10','11'],
    colors: ['White','Black','Tan'],
    stock: 20,
    isFeatured: true,
    isNew: false,
  },
  {
    name: 'Kids Dino Hoodie',
    description: 'Fun dinosaur print hoodie, super soft fleece.',
    price: 39.99,
    images: ['https://images.unsplash.com/photo-1522771930-78848d9293e8?w=500'],
    category: 'Kids',
    brand: 'DRIP Kids',
    sizes: ['2T','3T','4T','5','6','7','8'],
    colors: ['Green','Blue','Pink'],
    stock: 45,
    isFeatured: false,
    isNew: true,
  },
  {
    name: 'Oversized Bomber Jacket',
    description: 'Trendy oversized bomber with ribbed cuffs and hem.',
    price: 129.99,
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500'],
    category: 'Women',
    brand: 'DRIP Studio',
    sizes: ['XS','S','M','L'],
    colors: ['Black','Olive','Cream'],
    stock: 15,
    isFeatured: true,
    isNew: true,
  },
]);

console.log('✅ Fashion products seeded!');
process.exit();
